/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mcmc_Sampler */

#ifndef _Included_mcmc_Sampler
#define _Included_mcmc_Sampler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mcmc_Sampler
 * Method:    gibbsSample
 * Signature: (Lmcmc/ISampleable;Lmcmc/IParameter;Z)V
 */
JNIEXPORT void JNICALL Java_mcmc_Sampler_gibbsSample
  (JNIEnv *, jclass, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
